steps:
    # build the container images
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/react-books-frontend", "."]
      # push the container image to gcloud registry
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/react-books-frontend"]
    
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
      - 'run'
      - 'deploy'
      - 'myservice'
      - '--image'
      - 'gcr.io/$PROJECT_ID/react-books-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      
    - name: "gcr.io/cloud-builders/gcloud"
      args: ["app", "deploy","./app.yaml"]
    